### ISSUE TITLE
生产消息 Push(v string) 使用纳秒并不能保证key唯一 

### ISSUE THREAD

**Issue by gaoqin31** [zeromicro/go-queue#59]
Key:   []byte(strconv.FormatInt(time.Now().UnixNano(), 10))

生产消息 Push(v string) 使用纳秒并不能保证key唯一

**Comment by gaotangqi** [comment]
问题： https://developer.aliyun.com/article/1121501
set  nx  ex 同时执行有问题   导致锁失效问题
